language: python
python:
  - "3.6"

stages:
  - test

before_install:

  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a

  # Useful for debugging any issues with conda
  - conda info -a
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION pytorch-cpu scipy -c pytorch
  # - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then pip install enum34; fi
  - source activate test-environment

  - pip install future
  - pip install pytest pytest-cov codecov
  - pip install mock

install:

  - pip install .

script:
  - python -m pytest -s tests

deploy:
  provider: pypi
  user: qubvel
  password:
    secure: vUkfooHvfPJp4vA68pRwRehcEiAHZPMdDlWDiLZLYoYQNxR510/NRO6erWeRbv+Im4gmn/Z//ShpPlBs9L8kFz1Xf/PCWV6Xe661qpqvoNi9PBwtN4F33JryciR6VK8e+8mO9igWPSPueFUJ4y6xgcjgHWYg4W96iqO9tEh/rTHhPGgneWgWD4/k5NIE5XK5xg52kc28CNQTRepjN4PoRDtcj5Hv/kCKLpJXrFqPT4TJ7pUdU/sQUh4Epr9fn2AXOVh41IWOjvagUmYlx9QMdZpKtL0a83pe1SDDkDCxyTCuSBBdkVsPLZkFxq927Y29tarnSFmzm+Wxk6qcpwwVupCF+EGDK9goYS4czPiS8OjEKmFkLceZYjafZxCn6IUBoLcPUx5HmbsjkRIlNQAB8Mn2pYtH2kDCiNGtmVMH+VsML7HY7DqFCE8jvtP+caNLnGT4/q+ICKemzos5qsSL/6eu8sztTdgBTp8M2DAVyA51XFPKgeUnT5Ivi+r/skt/tUCzGrl8E3yUty6XW619x+bVggRgMq/RcUkItixnoaaVRx4AIiRN/scX5RmrQAgp6RxQ89o+NvrY0UeDVWUHvHcNxjogl8A8V7ROIwY/oxBF98Up2GJ1qtTKyNesBOZ09cxJHcTXeQBsI0ena+CLTFx/xfCQ5simMIEunn/x4+I=
  on:
    tags: true
  skip_existing: true